export default {
    "/letters": ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"],
    "/items?category=A": ["Name: Adriana", "Place or Location: Australia", "Animal: Antilope","Thing: Amoire"],
    "/items?category=B": ["Name: Bob", "Place or Location: Broad Ripple Village, Indianapolis, Indiana - USA", "Animal: Bobcat","Thing: bureau"],
    "/items?category=C": ["Name: Claire", "Place or Location: Claridges Hotel, London. UK", "Animal: Cheetah","Thing: Caravan"],
    "/items?category=D": ["Name: Dennis", "Place or Location: Denver", "Animal: Donkey","Thing: Doughnuts"],
    "/items?category=E": ["Name: Elsa", "Place or Location: Ecuador", "Animal: Elk","Thing: Electricity"],
    "/items?category=F": ["Name: Frederick", "Place or Location: Fort Worth, Texas - USA", "Animal: False Percula Clownfish, Amphiprion ocellaris","Thing: fresh produce section in a grocery store"],
    "/items?category=G": ["Name: Gina", "Place or Location: Greek Islands", "Animal: Giraffe","Thing: Goldfish Bowl"],
    "/items?category=H": ["Name: Halle", "Place or Location: Hotel", "Animal: Hippo","Thing: Highway"],
    "/items?category=I": ["Name: Ian", "Place or Location: Indiana", "Animal: Indigo","Thing: Ice"],
    "/items?category=J": ["Name: Justine", "Place or Location: Jerusalem", "Animal: Jackal","Thing: Jock-strap"],
    "/items?category=K": ["Name: Kathy", "Place or Location: Karachi", "Animal: King Cobra","Thing: Knee"],
    "/items?category=L": ["Name: Loni", "Place or Location: Las Vegas", "Animal: Leopard","Thing: Leotards"],
    "/items?category=M": ["Name: Mario", "Place or Location: Miami", "Animal: Marmot","Thing: Amoire"],
    "/items?category=N": ["Name: Nicole", "Place or Location: Nashua, NH", "Animal: Northern flying squirrel","Thing: Napkin"],
    "/items?category=O": ["Name: Ortal", "Place or Location: Ohio", "Animal: Octopus","Thing: Olive"],
    "/items?category=P": ["Name: Paola", "Place or Location: Paris", "Animal: Parrot","Thing: Plate"],
    "/items?category=Q": ["Name: Queenie", "Place or Location: Queen's Gate, Kensington, London, UK", "Animal: Quail","Thing: Queen Ann Bed Frame"],
    "/items?category=R": ["Name: Robert", "Place or Location: Ring road, Iceland", "Animal: Red Rainbowfish","Thing: Rocker"],
    "/items?category=S": ["Name: Samantha", "Place or Location: Sahara Desert", "Animal: Salamander","Thing: Stone"],
    "/items?category=T": ["Name: Terry", "Place or Location: Toronto,Ontario", "Animal: Toad","Thing: Tie"],
    "/items?category=U": ["Name: Ursula", "Place or Location: Ulm, Germany", "Animal: Umbrellabird","Thing: Underbrush"],
    "/items?category=V": ["Name: Vanessa", "Place or Location: Vineyard NSW AU", "Animal: Vicuna","Thing: AmoiVeilre"],
    "/items?category=W": ["Name: Walter", "Place or Location: Waterfall", "Animal: Wallaby","Thing: Window"],
    "/items?category=X": ["Name: Xavier", "Place or Location: Xalapa - Mexico", "Animal: Xenops","Thing: Xylanthrax"],
    "/items?category=Y": ["Name: Yvette", "Place or Location: Zanzibar, Ivory Coast", "Animal: Zebra","Thing: Yacht"],
    "/items?category=Z": ["Name: Zachary", "Place or Location: Australia", "Animal: Antilope","Thing: Zip"]
  };
